receivers:
  otlp:
    protocols:
      grpc:
      http:
processors:
  batch:
    timeout: 200ms
    send_batch_size: 512
exporters:
  otlp/jaeger:
    endpoint: jaeger:4317
    tls:
      insecure: true
  logging:
    verbosity: detailed
service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/jaeger, logging]