version: '3.8'

services:
  app:
    build: .
    container_name: app-aula-1
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.101.0
    container_name: otel-collector
    command: ["--config=/etc/otel-collector-config.yml"]
    volumes:
      - ./otel-collector/otel-collector-config.yml:/etc/otel-collector-config.yml
    ports:
      - "4317:4317" # OTLP gRPC
      - "4318:4318" # OTLP HTTP
    depends_on:
      - jaeger
  jaeger:
    image: jaegertracing/all-in-one:1.57
    container_name: jaeger
    ports:
      - "16686:16686"
      - "14268:14268"
      - "4317:4317" # Não é mais estritamente necessário expor no host, mas não há problema em deixar.
      - "4318:4318" # Idem.
    environment:
      - COLLECTOR_OTLP_ENABLED=true